interface UserData {
  cand: {
    admissiondate: string;
    cand_age: string;
    cand_bform: string;
    cand_bra_id: number;
    cand_class_id: number;
    cand_dob: string;
    cand_gender: string;
    cand_mothertongu: string;
    cand_name: string;
    cand_pic: string;
    cand_school_id: number;
    cand_section_id: number;
    cand_status: string;
    cand_user_id: number;
    created_at: string;
    family_id: string;
    form_id: string;
    id: number;
    nationality_id: number;
    par_id: number;
    religion_id: number;
    sibiling_status: string;
    student_id: string;
    updated_at: string;
  };
  cand_class: {
    branch_id: number;
    cls_name: string;
    cls_status: string;
    cls_user_id: number;
    created_at: string;
    id: number;
    school_id: number;
    updated_at: string;
  };
  cand_per: {
    created_at: string;
    id: number;
    per_address?: string | null;
    per_bra_id: number;
    per_cam_id: number;
    per_cand_id: number;
    per_contact1?: string | null;
    per_contact2?: string | null;
    per_date_from?: string | null;
    per_date_to?: string | null;
    per_email?: string | null;
    per_emergency_person1?: string | null;
    per_emergency_person2?: string | null;
    per_guardian_address?: string | null;
    per_guardian_cnic?: string | null;
    per_guardian_contact?: string | null;
    per_guardian_income?: string | null;
    per_guardian_name?: string | null;
    per_guardian_profession?: string | null;
    per_guardian_qualification?: string | null;
    per_guardian_relation?: string | null;
    per_homephone?: string | null;
    per_language?: string | null;
    per_last_school?: string | null;
    per_mobile?: string | null;
    per_pre_class?: string | null;
    per_pre_grades?: string | null;
    per_principal_contact?: string | null;
    per_principal_name?: string | null;
    per_reason?: string | null;
    per_relation_child1?: string | null;
    per_relation_child2?: string | null;
    per_religion?: string | null;
    per_school_id: number;
    per_status: string;
    per_user_id: number;
    per_whatsapp?: string | null;
    updated_at: string;
  };
  parent: {
    created_at: string;
    id: number;
    par_bra_id?: number | null;
    par_cam_id: number;
    par_cand_id: number;
    par_email?: string | null;
    par_fa_cnic: string;
    par_fa_monthlyincom: string;
    par_fa_nationality?: string | null;
    par_fa_organization?: string | null;
    par_fa_profession?: string | null;
    par_fa_qualification?: string | null;
    par_fathername: string;
    par_mo_cnic?: string | null;
    par_mo_monthlyincom?: string | null;
    par_mo_nationality?: string | null;
    par_mo_organization?: string | null;
    par_mo_profession?: string | null;
    par_mo_qualification?: string | null;
    par_mothername: string;
    par_school_id: number;
    par_status: string;
    par_user_id: number;
    parent_id: string;
    updated_at: string;
  };
}
